import { Department, InteractiveObject } from '../types/game';

export interface MapBounds {
  width: number;
  height: number;
}

export interface WallObstacle {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface GameMapDefinition {
  id: 'courtyard' | 'akl_lab' | 'otomotif_workshop' | 'tjkt_lab';
  title: string;
  subtitle: string;
  bounds: MapBounds;
  walls: WallObstacle[];
  objects: InteractiveObject[];
  spawnPoint: { x: number; y: number; direction: 'down' | 'up' | 'left' | 'right' };
}

export const MAPS: Record<'courtyard' | 'akl_lab' | 'otomotif_workshop' | 'tjkt_lab', GameMapDefinition> = {
  courtyard: {
    id: 'courtyard',
    title: 'SMK Muhammadiyah Bawang',
    subtitle: 'Main Gate & School Courtyard — Expo 2026',
    bounds: { width: 900, height: 600 },
    spawnPoint: { x: 450, y: 520, direction: 'up' },
    walls: [
      // Outer perimeter
      { x: 0, y: 0, width: 900, height: 30 },
      { x: 0, y: 570, width: 900, height: 30 },
      { x: 0, y: 0, width: 30, height: 600 },
      { x: 870, y: 0, width: 30, height: 600 },
      // Garden planters / decorative fountains
      { x: 120, y: 220, width: 80, height: 160 },
      { x: 700, y: 220, width: 80, height: 160 },
      // Central Expo Stage platform backdrop
      { x: 340, y: 50, width: 220, height: 40 },
    ],
    objects: [
      {
        id: 'mr_hendra_courtyard',
        name: 'Mr. Hendra (English Teacher & Expo Coordinator)',
        x: 450,
        y: 190,
        width: 32,
        height: 32,
        type: 'npc',
        label: 'Talk to Mr. Hendra',
        description: 'Mr. Hendra is wearing his distinctive teacher batik shirt, looking concerned about the missing Expo files.',
        highlight: true,
      },
      {
        id: 'expo_central_terminal',
        name: 'Digital Expo Archive Terminal',
        x: 450,
        y: 110,
        width: 48,
        height: 36,
        type: 'terminal',
        label: 'Expo Archive Console',
        description: 'The master terminal for the Muhiba Skill & Innovation Expo. The project description slot is blinking red!',
      },
      {
        id: 'door_akl',
        name: 'Door to AKL Accounting Lab',
        x: 100,
        y: 70,
        width: 50,
        height: 40,
        type: 'door',
        department: 'AKL',
        label: 'Enter AKL Lab',
        description: 'Entrance to the Accounting and Islamic Banking Laboratory.',
      },
      {
        id: 'door_otomotif',
        name: 'Door to Muhiba Automotive Workshop',
        x: 800,
        y: 70,
        width: 50,
        height: 40,
        type: 'door',
        department: 'OTOMOTIF',
        label: 'Enter Automotive Workshop',
        description: 'Entrance to the Muhiba Automotive Workshop.',
      },
      {
        id: 'door_tjkt',
        name: 'Door to TJKT Network Lab',
        x: 450,
        y: 35,
        width: 50,
        height: 35,
        type: 'door',
        department: 'TJKT',
        label: 'Enter TJKT Network Lab',
        description: 'Entrance to the Computer and Telecommunication Network Laboratory.',
      },
      {
        id: 'flagpole',
        name: 'Indonesian Flag & Muhiba Banner',
        x: 300,
        y: 300,
        width: 24,
        height: 24,
        type: 'object',
        label: 'School Courtyard Center',
        description: 'The Indonesian Red-and-White flag waving beside the Muhammadiyah crest.',
      },
    ],
  },

  akl_lab: {
    id: 'akl_lab',
    title: 'AKL Accounting Laboratory',
    subtitle: 'Department of Accounting and Islamic Banking',
    bounds: { width: 800, height: 550 },
    spawnPoint: { x: 400, y: 470, direction: 'up' },
    walls: [
      { x: 0, y: 0, width: 800, height: 30 },
      { x: 0, y: 520, width: 800, height: 30 },
      { x: 0, y: 0, width: 30, height: 550 },
      { x: 770, y: 0, width: 30, height: 550 },
      // Row of accounting desks
      { x: 100, y: 160, width: 220, height: 40 },
      { x: 480, y: 160, width: 220, height: 40 },
      { x: 100, y: 320, width: 220, height: 40 },
      { x: 480, y: 320, width: 220, height: 40 },
    ],
    objects: [
      {
        id: 'exit_door_akl',
        name: 'Exit to Courtyard',
        x: 400,
        y: 500,
        width: 50,
        height: 20,
        type: 'door',
        label: 'Return to Courtyard',
        description: 'Door leading back to the SMK Muhammadiyah Bawang courtyard.',
      },
      {
        id: 'naya_npc',
        name: 'Naya (AKL Student Representative)',
        x: 400,
        y: 240,
        width: 32,
        height: 32,
        type: 'npc',
        department: 'AKL',
        label: 'Talk to Naya',
        description: 'Naya is holding an accounting journal, working diligently on the Smart Financial Dashboard project.',
        highlight: true,
      },
      {
        id: 'akl_computers',
        name: 'Modern Computers',
        x: 180,
        y: 130,
        width: 44,
        height: 30,
        type: 'object',
        label: 'Modern Computers',
        description: 'High-speed desktop computers running Islamic banking ledger software and spreadsheet models.',
        questStep: 1,
      },
      {
        id: 'akl_ledger',
        name: 'Organized Ledger & Books',
        x: 560,
        y: 130,
        width: 38,
        height: 30,
        type: 'object',
        label: 'Accounting Ledger',
        description: 'A neatly organized physical ledger with meticulous debit and credit balance entries.',
        questStep: 1,
      },
      {
        id: 'akl_calculator',
        name: 'Accurate Financial Calculator',
        x: 180,
        y: 290,
        width: 36,
        height: 30,
        type: 'object',
        label: 'Financial Calculator',
        description: 'A multi-function financial calculator used for rapid and accurate balance auditing.',
        questStep: 1,
      },
      {
        id: 'akl_printer',
        name: 'High-Speed Laser Printer',
        x: 560,
        y: 290,
        width: 40,
        height: 30,
        type: 'object',
        label: 'Network Printer',
        description: 'A laser printer producing clean Islamic banking financial statements.',
        questStep: 1,
      },
      {
        id: 'akl_filing_cabinet',
        name: 'Filing Cabinet',
        x: 720,
        y: 80,
        width: 40,
        height: 60,
        type: 'object',
        label: 'Filing Cabinet',
        description: 'A metallic cabinet where historical transaction archives and audit sheets are safely stored.',
        questStep: 1,
      },
      {
        id: 'akl_main_terminal',
        name: 'Smart Financial Dashboard Station',
        x: 400,
        y: 70,
        width: 60,
        height: 40,
        type: 'terminal',
        label: 'Smart Financial Terminal',
        description: 'The master workstation hosting the Smart Financial Dashboard demo.',
        questStep: 5,
        highlight: true,
      },
    ],
  },

  otomotif_workshop: {
    id: 'otomotif_workshop',
    title: 'Muhiba Automotive Workshop',
    subtitle: 'Department of Automotive Engineering',
    bounds: { width: 850, height: 580 },
    spawnPoint: { x: 425, y: 500, direction: 'up' },
    walls: [
      { x: 0, y: 0, width: 850, height: 30 },
      { x: 0, y: 550, width: 850, height: 30 },
      { x: 0, y: 0, width: 30, height: 580 },
      { x: 820, y: 0, width: 30, height: 580 },
      // Hydraulic lift area & workbench
      { x: 120, y: 150, width: 180, height: 60 },
      { x: 550, y: 150, width: 220, height: 60 },
      { x: 550, y: 340, width: 220, height: 60 },
    ],
    objects: [
      {
        id: 'exit_door_otomotif',
        name: 'Exit to Courtyard',
        x: 425,
        y: 530,
        width: 50,
        height: 20,
        type: 'door',
        label: 'Return to Courtyard',
        description: 'Door leading back to the school courtyard.',
      },
      {
        id: 'raka_npc',
        name: 'Raka (Automotive Student Lead)',
        x: 350,
        y: 260,
        width: 32,
        height: 32,
        type: 'npc',
        department: 'OTOMOTIF',
        label: 'Talk to Raka',
        description: 'Raka is in his blue workshop jumpsuit with safety goggles, examining the electric motorcycle.',
        highlight: true,
      },
      {
        id: 'electric_motorcycle',
        name: 'Smart Electric Motorcycle',
        x: 425,
        y: 230,
        width: 70,
        height: 50,
        type: 'object',
        label: 'Smart Electric Motorcycle',
        description: 'The prized student innovation: a sleek, eco-friendly electric motorbike with IoT integration.',
        questStep: 1,
        highlight: true,
      },
      {
        id: 'moto_battery',
        name: 'Lithium Battery Pack',
        x: 425,
        y: 190,
        width: 36,
        height: 28,
        type: 'object',
        label: 'High-Capacity Battery',
        description: 'A modular 72V lithium battery pack positioned beneath the motorcycle seat.',
        questStep: 1,
      },
      {
        id: 'moto_headlight',
        name: 'Aerodynamic LED Headlight',
        x: 460,
        y: 210,
        width: 24,
        height: 24,
        type: 'object',
        label: 'LED Headlight',
        description: 'A sleek, energy-efficient LED light with adaptive daytime running brightness.',
        questStep: 1,
      },
      {
        id: 'moto_dashboard',
        name: 'Digital Touchscreen Dashboard',
        x: 395,
        y: 210,
        width: 28,
        height: 24,
        type: 'object',
        label: 'Digital Dashboard',
        description: 'An advanced digital display above the handlebar showing battery telemetry and speed.',
        questStep: 1,
      },
      {
        id: 'moto_motor',
        name: 'Brushless Electric Motor',
        x: 450,
        y: 260,
        width: 32,
        height: 28,
        type: 'object',
        label: 'Electric Motor',
        description: 'A powerful 3000W brushless hub motor installed directly into the rear wheel.',
        questStep: 1,
      },
      {
        id: 'oto_diagnostic_station',
        name: 'Diagnostic Scanner Station',
        x: 200,
        y: 120,
        width: 50,
        height: 34,
        type: 'terminal',
        label: 'Diagnostic Terminal',
        description: 'Electronic diagnostic scanner connected to the motorcycle computer.',
        questStep: 5,
        highlight: true,
      },
      {
        id: 'oto_toolbox',
        name: 'Heavy Duty Tool Cabinet',
        x: 650,
        y: 120,
        width: 44,
        height: 30,
        type: 'object',
        label: 'Tool Cabinet',
        description: 'Organized sets of wrenches, torque ratchets, and insulated electrical screwdrivers.',
      },
    ],
  },

  tjkt_lab: {
    id: 'tjkt_lab',
    title: 'TJKT Network Laboratory',
    subtitle: 'Department of Computer and Telecommunication Network',
    bounds: { width: 840, height: 560 },
    spawnPoint: { x: 420, y: 490, direction: 'up' },
    walls: [
      { x: 0, y: 0, width: 840, height: 30 },
      { x: 0, y: 530, width: 840, height: 30 },
      { x: 0, y: 0, width: 30, height: 560 },
      { x: 810, y: 0, width: 30, height: 560 },
      // Server rack enclosures and lab tables
      { x: 100, y: 150, width: 200, height: 50 },
      { x: 540, y: 150, width: 220, height: 50 },
      { x: 100, y: 320, width: 200, height: 50 },
      { x: 540, y: 320, width: 220, height: 50 },
    ],
    objects: [
      {
        id: 'exit_door_tjkt',
        name: 'Exit to Courtyard',
        x: 420,
        y: 510,
        width: 50,
        height: 20,
        type: 'door',
        label: 'Return to Courtyard',
        description: 'Door leading back to the courtyard.',
      },
      {
        id: 'dimas_npc',
        name: 'Dimas (TJKT Network Administrator)',
        x: 420,
        y: 250,
        width: 32,
        height: 32,
        type: 'npc',
        department: 'TJKT',
        label: 'Talk to Dimas',
        description: 'Dimas is holding a network tester and patch cable, looking bewildered at the offline server state.',
        highlight: true,
      },
      {
        id: 'tjkt_server',
        name: 'High-Capacity School Server',
        x: 420,
        y: 90,
        width: 60,
        height: 50,
        type: 'terminal',
        label: 'Server Rack',
        description: 'The central enterprise rack server running the Expo website and digital database.',
        questStep: 1,
        highlight: true,
      },
      {
        id: 'tjkt_router',
        name: 'Gigabit Core Router',
        x: 200,
        y: 120,
        width: 44,
        height: 30,
        type: 'object',
        label: 'Core Router',
        description: 'A high-throughput enterprise router routing packets between subnets.',
        questStep: 1,
      },
      {
        id: 'tjkt_switch',
        name: 'Managed Distribution Switch',
        x: 640,
        y: 120,
        width: 48,
        height: 30,
        type: 'object',
        label: 'Managed Switch',
        description: 'A 24-port Gigabit switch with active VLAN configuration.',
        questStep: 1,
      },
      {
        id: 'tjkt_cables',
        name: 'Cat6 Ethernet Cables',
        x: 200,
        y: 290,
        width: 40,
        height: 30,
        type: 'object',
        label: 'Ethernet Cables',
        description: 'Color-coded high-bandwidth twisted-pair cables with RJ45 connectors.',
        questStep: 1,
      },
      {
        id: 'tjkt_monitor',
        name: 'Network Monitoring Display',
        x: 640,
        y: 290,
        width: 46,
        height: 30,
        type: 'object',
        label: 'Monitoring Display',
        description: 'Multi-screen monitor displaying live bandwidth and packet latency.',
        questStep: 1,
      },
    ],
  },
};
